// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC83OgBGvuLugvgPpxPHNIcAMSAWpUxxAs',
    appId: '1:601679780958:web:63119c396c8609503be8cf',
    messagingSenderId: '601679780958',
    projectId: 'test-oauth2-3b9a0',
    authDomain: 'test-oauth2-3b9a0.firebaseapp.com',
    storageBucket: 'test-oauth2-3b9a0.appspot.com',
    measurementId: 'G-YWVB9K4FCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm8QmwKgahVJBKB70ekORqSxbJLIU9Dxw',
    appId: '1:601679780958:android:ab800eefb5720b953be8cf',
    messagingSenderId: '601679780958',
    projectId: 'test-oauth2-3b9a0',
    storageBucket: 'test-oauth2-3b9a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHUx6nGyA_JkPx50kGm8-62sxP8ylM6qc',
    appId: '1:601679780958:ios:49943166f88e221d3be8cf',
    messagingSenderId: '601679780958',
    projectId: 'test-oauth2-3b9a0',
    storageBucket: 'test-oauth2-3b9a0.appspot.com',
    iosClientId: '601679780958-1k8vn0lq489dgq4acffos9ti920em3ji.apps.googleusercontent.com',
    iosBundleId: 'com.example.testOauth2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHUx6nGyA_JkPx50kGm8-62sxP8ylM6qc',
    appId: '1:601679780958:ios:49943166f88e221d3be8cf',
    messagingSenderId: '601679780958',
    projectId: 'test-oauth2-3b9a0',
    storageBucket: 'test-oauth2-3b9a0.appspot.com',
    iosClientId: '601679780958-1k8vn0lq489dgq4acffos9ti920em3ji.apps.googleusercontent.com',
    iosBundleId: 'com.example.testOauth2',
  );
}
